// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: directories.sql

package db

import (
	"context"
	"database/sql"
)

const createDirectory = `-- name: CreateDirectory :exec
INSERT INTO directories (id, space_id, parent_id, name, slug, position, icon, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDirectoryParams struct {
	ID        string         `json:"id"`
	SpaceID   sql.NullString `json:"space_id"`
	ParentID  sql.NullString `json:"parent_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Position  sql.NullInt64  `json:"position"`
	Icon      sql.NullString `json:"icon"`
	CreatedBy sql.NullString `json:"created_by"`
}

func (q *Queries) CreateDirectory(ctx context.Context, arg CreateDirectoryParams) error {
	_, err := q.db.ExecContext(ctx, createDirectory,
		arg.ID,
		arg.SpaceID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Position,
		arg.Icon,
		arg.CreatedBy,
	)
	return err
}

const deleteDirectory = `-- name: DeleteDirectory :exec
DELETE FROM directories WHERE id = ?
`

func (q *Queries) DeleteDirectory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDirectory, id)
	return err
}

const getDirectory = `-- name: GetDirectory :one
SELECT id, space_id, parent_id, name, slug, position, icon, created_by, created_at, updated_at
FROM directories
WHERE id = ?
`

func (q *Queries) GetDirectory(ctx context.Context, id string) (Directory, error) {
	row := q.db.QueryRowContext(ctx, getDirectory, id)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.Icon,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectoryBySlug = `-- name: GetDirectoryBySlug :one
SELECT id, space_id, parent_id, name, slug, position, icon, created_by, created_at, updated_at
FROM directories
WHERE space_id = ? AND slug = ?
`

type GetDirectoryBySlugParams struct {
	SpaceID sql.NullString `json:"space_id"`
	Slug    string         `json:"slug"`
}

func (q *Queries) GetDirectoryBySlug(ctx context.Context, arg GetDirectoryBySlugParams) (Directory, error) {
	row := q.db.QueryRowContext(ctx, getDirectoryBySlug, arg.SpaceID, arg.Slug)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.Icon,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxDirectoryPosition = `-- name: GetMaxDirectoryPosition :one
SELECT COALESCE(MAX(position), -1) FROM directories WHERE parent_id = ?
`

func (q *Queries) GetMaxDirectoryPosition(ctx context.Context, parentID sql.NullString) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxDirectoryPosition, parentID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listDirectorySubdirectories = `-- name: ListDirectorySubdirectories :many
SELECT id, space_id, parent_id, name, slug, position, icon, created_by, created_at, updated_at
FROM directories
WHERE parent_id = ?
ORDER BY position
`

func (q *Queries) ListDirectorySubdirectories(ctx context.Context, parentID sql.NullString) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, listDirectorySubdirectories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Directory{}
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Position,
			&i.Icon,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDirectories = `-- name: ListRootDirectories :many
SELECT id, space_id, parent_id, name, slug, position, icon, created_by, created_at, updated_at
FROM directories
WHERE space_id = ? AND parent_id IS NULL
ORDER BY position
`

func (q *Queries) ListRootDirectories(ctx context.Context, spaceID sql.NullString) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, listRootDirectories, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Directory{}
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Position,
			&i.Icon,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirectoryIcon = `-- name: UpdateDirectoryIcon :exec
UPDATE directories
SET icon = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateDirectoryIconParams struct {
	Icon sql.NullString `json:"icon"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateDirectoryIcon(ctx context.Context, arg UpdateDirectoryIconParams) error {
	_, err := q.db.ExecContext(ctx, updateDirectoryIcon, arg.Icon, arg.ID)
	return err
}

const updateDirectoryName = `-- name: UpdateDirectoryName :exec
UPDATE directories
SET name = ?, slug = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateDirectoryNameParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateDirectoryName(ctx context.Context, arg UpdateDirectoryNameParams) error {
	_, err := q.db.ExecContext(ctx, updateDirectoryName, arg.Name, arg.Slug, arg.ID)
	return err
}

const updateDirectoryPosition = `-- name: UpdateDirectoryPosition :exec
UPDATE directories
SET position = ?, parent_id = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateDirectoryPositionParams struct {
	Position sql.NullInt64  `json:"position"`
	ParentID sql.NullString `json:"parent_id"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateDirectoryPosition(ctx context.Context, arg UpdateDirectoryPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateDirectoryPosition, arg.Position, arg.ParentID, arg.ID)
	return err
}
