// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT OR IGNORE INTO group_members (group_id, user_id) VALUES (?, ?)
`

type AddGroupMemberParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (id, name) VALUES (?, ?)
`

type CreateGroupParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup, arg.ID, arg.Name)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.email, u.name, u.global_role, u.created_at
FROM users u
JOIN group_members gm ON gm.user_id = u.id
WHERE gm.group_id = ?
ORDER BY u.email
`

type ListGroupMembersRow struct {
	ID         string         `json:"id"`
	Email      string         `json:"email"`
	Name       sql.NullString `json:"name"`
	GlobalRole sql.NullString `json:"global_role"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.GlobalRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, created_at FROM groups ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.created_at
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = ?
ORDER BY g.name
`

func (q *Queries) ListUserGroups(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = ? AND user_id = ?
`

type RemoveGroupMemberParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups SET name = ? WHERE id = ?
`

type UpdateGroupParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.Name, arg.ID)
	return err
}
