// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Directory struct {
	ID        string         `json:"id"`
	SpaceID   sql.NullString `json:"space_id"`
	ParentID  sql.NullString `json:"parent_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Position  sql.NullInt64  `json:"position"`
	Icon      sql.NullString `json:"icon"`
	CreatedBy sql.NullString `json:"created_by"`
	CreatedAt sql.NullInt64  `json:"created_at"`
	UpdatedAt sql.NullInt64  `json:"updated_at"`
}

type Group struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	CreatedAt sql.NullInt64 `json:"created_at"`
}

type GroupMember struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

type McpToken struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	TokenPrefix string         `json:"token_prefix"`
	TokenHash   string         `json:"token_hash"`
	Scopes      string         `json:"scopes"`
	SpaceID     sql.NullString `json:"space_id"`
	LastUsedAt  sql.NullInt64  `json:"last_used_at"`
	CreatedAt   int64          `json:"created_at"`
	ExpiresAt   sql.NullInt64  `json:"expires_at"`
}

type Page struct {
	ID          string         `json:"id"`
	SpaceID     sql.NullString `json:"space_id"`
	DirectoryID sql.NullString `json:"directory_id"`
	Title       sql.NullString `json:"title"`
	Slug        sql.NullString `json:"slug"`
	Position    sql.NullInt64  `json:"position"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
	Icon        sql.NullString `json:"icon"`
}

type PageSnapshot struct {
	ID          string         `json:"id"`
	PageID      sql.NullString `json:"page_id"`
	YjsSnapshot []byte         `json:"yjs_snapshot"`
	Markdown    sql.NullString `json:"markdown"`
	AuthorID    sql.NullString `json:"author_id"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	Label       sql.NullString `json:"label"`
	IsCompacted sql.NullInt64  `json:"is_compacted"`
}

type Permission struct {
	ID          string         `json:"id"`
	TargetType  string         `json:"target_type"`
	TargetID    string         `json:"target_id"`
	GranteeType string         `json:"grantee_type"`
	GranteeID   string         `json:"grantee_id"`
	Level       int64          `json:"level"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
}

type RefreshToken struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	TokenHash string        `json:"token_hash"`
	ExpiresAt int64         `json:"expires_at"`
	CreatedAt sql.NullInt64 `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Space struct {
	ID                    string         `json:"id"`
	WorkspaceID           sql.NullString `json:"workspace_id"`
	Name                  string         `json:"name"`
	Slug                  string         `json:"slug"`
	DefaultPermission     sql.NullString `json:"default_permission"`
	McpWriteEnabled       sql.NullInt64  `json:"mcp_write_enabled"`
	SnapshotRetentionDays sql.NullInt64  `json:"snapshot_retention_days"`
	CreatedAt             sql.NullInt64  `json:"created_at"`
	Icon                  string         `json:"icon"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	Name         sql.NullString `json:"name"`
	PasswordHash string         `json:"password_hash"`
	GlobalRole   sql.NullString `json:"global_role"`
	CreatedAt    sql.NullInt64  `json:"created_at"`
	DeletedAt    sql.NullInt64  `json:"deleted_at"`
}
