// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pages.sql

package db

import (
	"context"
	"database/sql"
)

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (id, space_id, directory_id, title, slug, position, created_by, icon)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePageParams struct {
	ID          string         `json:"id"`
	SpaceID     sql.NullString `json:"space_id"`
	DirectoryID sql.NullString `json:"directory_id"`
	Title       sql.NullString `json:"title"`
	Slug        sql.NullString `json:"slug"`
	Position    sql.NullInt64  `json:"position"`
	CreatedBy   sql.NullString `json:"created_by"`
	Icon        sql.NullString `json:"icon"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.ID,
		arg.SpaceID,
		arg.DirectoryID,
		arg.Title,
		arg.Slug,
		arg.Position,
		arg.CreatedBy,
		arg.Icon,
	)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const getMaxPagePosition = `-- name: GetMaxPagePosition :one
SELECT COALESCE(MAX(position), -1) FROM pages WHERE directory_id = ?
`

func (q *Queries) GetMaxPagePosition(ctx context.Context, directoryID sql.NullString) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxPagePosition, directoryID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPage = `-- name: GetPage :one
SELECT id, space_id, directory_id, title, slug, position, created_by, created_at, updated_at, icon
FROM pages
WHERE id = ?
`

func (q *Queries) GetPage(ctx context.Context, id string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.DirectoryID,
		&i.Title,
		&i.Slug,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, space_id, directory_id, title, slug, position, created_by, created_at, updated_at, icon
FROM pages
WHERE space_id = ? AND slug = ?
`

type GetPageBySlugParams struct {
	SpaceID sql.NullString `json:"space_id"`
	Slug    sql.NullString `json:"slug"`
}

func (q *Queries) GetPageBySlug(ctx context.Context, arg GetPageBySlugParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageBySlug, arg.SpaceID, arg.Slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.DirectoryID,
		&i.Title,
		&i.Slug,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}

const getPagesBySlugPrefix = `-- name: GetPagesBySlugPrefix :many
SELECT id, space_id, directory_id, title, slug, position, created_by, created_at, updated_at, icon
FROM pages
WHERE space_id = ? AND slug LIKE ?
ORDER BY slug
`

type GetPagesBySlugPrefixParams struct {
	SpaceID sql.NullString `json:"space_id"`
	Slug    sql.NullString `json:"slug"`
}

func (q *Queries) GetPagesBySlugPrefix(ctx context.Context, arg GetPagesBySlugPrefixParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, getPagesBySlugPrefix, arg.SpaceID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.DirectoryID,
			&i.Title,
			&i.Slug,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPages = `-- name: ListMyPages :many
SELECT p.id, p.space_id, p.directory_id, p.title, p.slug, p.position, p.created_by, p.created_at, p.updated_at, p.icon
FROM pages p
JOIN spaces s ON p.space_id = s.id
WHERE p.created_by = ?
ORDER BY p.updated_at DESC
LIMIT ?
`

type ListMyPagesParams struct {
	CreatedBy sql.NullString `json:"created_by"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListMyPages(ctx context.Context, arg ListMyPagesParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listMyPages, arg.CreatedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.DirectoryID,
			&i.Title,
			&i.Slug,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesByDirectory = `-- name: ListPagesByDirectory :many
SELECT id, space_id, directory_id, title, slug, position, created_by, created_at, updated_at, icon
FROM pages
WHERE directory_id = ?
ORDER BY position
`

func (q *Queries) ListPagesByDirectory(ctx context.Context, directoryID sql.NullString) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPagesByDirectory, directoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.DirectoryID,
			&i.Title,
			&i.Slug,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPages = `-- name: ListRecentPages :many
SELECT p.id, p.space_id, p.directory_id, p.title, p.slug, p.position, p.created_by, p.created_at, p.updated_at, p.icon
FROM pages p
JOIN spaces s ON p.space_id = s.id
ORDER BY p.updated_at DESC
LIMIT ?
`

func (q *Queries) ListRecentPages(ctx context.Context, limit int64) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.DirectoryID,
			&i.Title,
			&i.Slug,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootPages = `-- name: ListRootPages :many
SELECT id, space_id, directory_id, title, slug, position, created_by, created_at, updated_at, icon
FROM pages
WHERE space_id = ? AND directory_id IS NULL
ORDER BY position
`

func (q *Queries) ListRootPages(ctx context.Context, spaceID sql.NullString) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listRootPages, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.DirectoryID,
			&i.Title,
			&i.Slug,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePageIcon = `-- name: UpdatePageIcon :exec
UPDATE pages
SET icon = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdatePageIconParams struct {
	Icon sql.NullString `json:"icon"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdatePageIcon(ctx context.Context, arg UpdatePageIconParams) error {
	_, err := q.db.ExecContext(ctx, updatePageIcon, arg.Icon, arg.ID)
	return err
}

const updatePagePosition = `-- name: UpdatePagePosition :exec
UPDATE pages
SET position = ?, directory_id = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdatePagePositionParams struct {
	Position    sql.NullInt64  `json:"position"`
	DirectoryID sql.NullString `json:"directory_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdatePagePosition(ctx context.Context, arg UpdatePagePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePagePosition, arg.Position, arg.DirectoryID, arg.ID)
	return err
}

const updatePageTitle = `-- name: UpdatePageTitle :exec
UPDATE pages
SET title = ?, slug = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdatePageTitleParams struct {
	Title sql.NullString `json:"title"`
	Slug  sql.NullString `json:"slug"`
	ID    string         `json:"id"`
}

func (q *Queries) UpdatePageTitle(ctx context.Context, arg UpdatePageTitleParams) error {
	_, err := q.db.ExecContext(ctx, updatePageTitle, arg.Title, arg.Slug, arg.ID)
	return err
}
