// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissions.sql

package db

import (
	"context"
	"database/sql"
)

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE target_type = ? AND target_id = ? AND grantee_type = ? AND grantee_id = ?
`

type DeletePermissionParams struct {
	TargetType  string `json:"target_type"`
	TargetID    string `json:"target_id"`
	GranteeType string `json:"grantee_type"`
	GranteeID   string `json:"grantee_id"`
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.ExecContext(ctx, deletePermission,
		arg.TargetType,
		arg.TargetID,
		arg.GranteeType,
		arg.GranteeID,
	)
	return err
}

const deletePermissionsByGrantee = `-- name: DeletePermissionsByGrantee :exec
DELETE FROM permissions WHERE grantee_type = ? AND grantee_id = ?
`

type DeletePermissionsByGranteeParams struct {
	GranteeType string `json:"grantee_type"`
	GranteeID   string `json:"grantee_id"`
}

func (q *Queries) DeletePermissionsByGrantee(ctx context.Context, arg DeletePermissionsByGranteeParams) error {
	_, err := q.db.ExecContext(ctx, deletePermissionsByGrantee, arg.GranteeType, arg.GranteeID)
	return err
}

const deletePermissionsForTarget = `-- name: DeletePermissionsForTarget :exec
DELETE FROM permissions WHERE target_type = ? AND target_id = ?
`

type DeletePermissionsForTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) DeletePermissionsForTarget(ctx context.Context, arg DeletePermissionsForTargetParams) error {
	_, err := q.db.ExecContext(ctx, deletePermissionsForTarget, arg.TargetType, arg.TargetID)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT id, target_type, target_id, grantee_type, grantee_id, level, created_by, created_at, updated_at
FROM permissions
WHERE target_type = ? AND target_id = ? AND grantee_type = ? AND grantee_id = ?
`

type GetPermissionParams struct {
	TargetType  string `json:"target_type"`
	TargetID    string `json:"target_id"`
	GranteeType string `json:"grantee_type"`
	GranteeID   string `json:"grantee_id"`
}

func (q *Queries) GetPermission(ctx context.Context, arg GetPermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermission,
		arg.TargetType,
		arg.TargetID,
		arg.GranteeType,
		arg.GranteeID,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Level,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissionsByGrantee = `-- name: ListPermissionsByGrantee :many
SELECT id, target_type, target_id, grantee_type, grantee_id, level, created_by, created_at, updated_at
FROM permissions
WHERE grantee_type = ? AND grantee_id = ?
ORDER BY target_type, target_id
`

type ListPermissionsByGranteeParams struct {
	GranteeType string `json:"grantee_type"`
	GranteeID   string `json:"grantee_id"`
}

func (q *Queries) ListPermissionsByGrantee(ctx context.Context, arg ListPermissionsByGranteeParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByGrantee, arg.GranteeType, arg.GranteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Level,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByTarget = `-- name: ListPermissionsByTarget :many
SELECT id, target_type, target_id, grantee_type, grantee_id, level, created_by, created_at, updated_at
FROM permissions
WHERE target_type = ? AND target_id = ?
ORDER BY grantee_type, grantee_id
`

type ListPermissionsByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) ListPermissionsByTarget(ctx context.Context, arg ListPermissionsByTargetParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Level,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByTargetAndGrantee = `-- name: ListPermissionsByTargetAndGrantee :many
SELECT id, target_type, target_id, grantee_type, grantee_id, level, created_by, created_at, updated_at
FROM permissions
WHERE target_type = ? AND target_id = ? AND grantee_type = ?
ORDER BY grantee_id
`

type ListPermissionsByTargetAndGranteeParams struct {
	TargetType  string `json:"target_type"`
	TargetID    string `json:"target_id"`
	GranteeType string `json:"grantee_type"`
}

func (q *Queries) ListPermissionsByTargetAndGrantee(ctx context.Context, arg ListPermissionsByTargetAndGranteeParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByTargetAndGrantee, arg.TargetType, arg.TargetID, arg.GranteeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Level,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPermission = `-- name: UpsertPermission :exec
INSERT INTO permissions (id, target_type, target_id, grantee_type, grantee_id, level, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_type, target_id, grantee_type, grantee_id)
DO UPDATE SET level = excluded.level, updated_at = excluded.updated_at
`

type UpsertPermissionParams struct {
	ID          string         `json:"id"`
	TargetType  string         `json:"target_type"`
	TargetID    string         `json:"target_id"`
	GranteeType string         `json:"grantee_type"`
	GranteeID   string         `json:"grantee_id"`
	Level       int64          `json:"level"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPermission,
		arg.ID,
		arg.TargetType,
		arg.TargetID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Level,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
