// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: spaces.sql

package db

import (
	"context"
	"database/sql"
)

const createSpace = `-- name: CreateSpace :exec
INSERT INTO spaces (id, name, slug, default_permission, mcp_write_enabled, snapshot_retention_days)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSpaceParams struct {
	ID                    string         `json:"id"`
	Name                  string         `json:"name"`
	Slug                  string         `json:"slug"`
	DefaultPermission     sql.NullString `json:"default_permission"`
	McpWriteEnabled       sql.NullInt64  `json:"mcp_write_enabled"`
	SnapshotRetentionDays sql.NullInt64  `json:"snapshot_retention_days"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) error {
	_, err := q.db.ExecContext(ctx, createSpace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.DefaultPermission,
		arg.McpWriteEnabled,
		arg.SnapshotRetentionDays,
	)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = ?
`

func (q *Queries) DeleteSpace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSpace, id)
	return err
}

const getSpace = `-- name: GetSpace :one
SELECT id, workspace_id, name, slug, default_permission, mcp_write_enabled, snapshot_retention_days, created_at
FROM spaces
WHERE id = ?
`

func (q *Queries) GetSpace(ctx context.Context, id string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpace, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.DefaultPermission,
		&i.McpWriteEnabled,
		&i.SnapshotRetentionDays,
		&i.CreatedAt,
	)
	return i, err
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, workspace_id, name, slug, default_permission, mcp_write_enabled, snapshot_retention_days, created_at
FROM spaces
WHERE slug = ?
`

func (q *Queries) GetSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.DefaultPermission,
		&i.McpWriteEnabled,
		&i.SnapshotRetentionDays,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, workspace_id, name, slug, default_permission, mcp_write_enabled, snapshot_retention_days, created_at
FROM spaces
ORDER BY name
`

func (q *Queries) ListSpaces(ctx context.Context) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.DefaultPermission,
			&i.McpWriteEnabled,
			&i.SnapshotRetentionDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :exec
UPDATE spaces
SET name = ?, default_permission = ?, mcp_write_enabled = ?, snapshot_retention_days = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSpaceParams struct {
	Name                  string         `json:"name"`
	DefaultPermission     sql.NullString `json:"default_permission"`
	McpWriteEnabled       sql.NullInt64  `json:"mcp_write_enabled"`
	SnapshotRetentionDays sql.NullInt64  `json:"snapshot_retention_days"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) error {
	_, err := q.db.ExecContext(ctx, updateSpace,
		arg.Name,
		arg.DefaultPermission,
		arg.McpWriteEnabled,
		arg.SnapshotRetentionDays,
		arg.ID,
	)
	return err
}
